name: Windows-CRD
on: workflow_dispatch

jobs:
  crd:
    runs-on: windows-latest

    env:
      CRD_AUTH_CODE: ${{ secrets.CRD_AUTH_CODE }}
      CRD_PIN: ${{ secrets.CRD_PIN }}

    steps:
      - name: Install Chrome
        run: |
          curl -o chrome_installer.exe https://dl.google.com/chrome/install/latest/chrome_installer.exe
          start /wait chrome_installer.exe /silent /install

      - name: Install Chrome Remote Desktop Host
        run: |
          curl -o crdhost.msi https://dl.google.com/chrome-remote-desktop/chrome-remote-desktop_current_amd64.msi
          msiexec /i crdhost.msi /quiet

      - name: Register Chrome Remote Desktop
        run: |
          "C:\Program Files\Google\Chrome Remote Desktop\remoting_start_host.exe" ^
            --code="${env:CRD_AUTH_CODE}" ^
            --redirect-url="https://remotedesktop.google.com/_/oauthredirect" ^
            --name="GITHUB-WIN" ^
            --pin="${env:CRD_PIN}"

      - name: Keep Alive
        run: ping -t 127.0.0.1
