name: Windows-RDP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Enable RDP + Create User
        run: |
          net user runneradmin /active:yes
          net user rdpuser "Password123!" /add
          net localgroup administrators rdpuser /add

          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f

          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes

      - name: Show RDP Login
        run: |
          hostname
          echo "=========================="
          echo "RDP Enabled Successfully!"
          echo "Username: rdpuser"
          echo "Password: Password123!"
          echo "Copy your IP from below:"
          ipconfig

      - name: Keep Session Alive
        run: |
          ping -n 999999 127.0.0.1 > nul
