name: Windows-CRD
on:
  workflow_dispatch:

jobs:
  crd:
    runs-on: windows-latest
    env:
      CRD_AUTH_CODE: ${{ secrets.CRD_AUTH_CODE }}
      CRD_PIN: ${{ secrets.CRD_PIN }}

    steps:
      - name: Install Chrome Remote Desktop Host
        shell: powershell
        run: |
          Write-Host "Downloading Chrome Remote Desktop Host..."
          Invoke-WebRequest `
            -Uri "https://dl.google.com/chrome-remote-desktop/chrome-remote-desktop_current_amd64.msi" `
            -OutFile "chrome-remote-desktop-host.msi" `
            -UseBasicParsing

          Write-Host "Installing CRD Host..."
          Start-Process "msiexec.exe" -ArgumentList "/i chrome-remote-desktop-host.msi /qn" -Wait

      - name: Start Chrome Remote Desktop Host
        shell: powershell
        run: |
          $AuthCode = "${{ secrets.CRD_AUTH_CODE }}"
          $Pin = "${{ secrets.CRD_PIN }}"
          $CRDPath = "${env:ProgramFiles(x86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"

          Write-Host "Starting Chrome Remote Desktop Host..."
          Start-Process $CRDPath `
            -ArgumentList "--code=$AuthCode", "--redirect-url=https://remotedesktop.google.com/_/oauthredirect", "--name=GitHub-Windows", "--pin=$Pin" `
            -Wait

      - name: Keep Runner Alive
        shell: powershell
        run: |
          Write-Host "Keeping the session alive..."
          ping -t 127.0.0.1
