name: Master Launcher

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  launch-all:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger all workflows
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh workflow run main.yml
          
  next-job:
    needs: launch-all
    runs-on: ubuntu-latest

    steps:
      - name: Continue
        run: |
          echo "All workflows have been started."
